function renderReport(text) {
  if (!text) return null
  const sections = text.split(/\n(?=## )/)
  return sections.map((section, i) => {
    const lines   = section.split('\n')
    const heading = lines[0].replace(/^##\s*/, '').trim()
    const body    = lines.slice(1).join('\n').trim()
    const items   = body.split('\n').filter(l => l.trim())

    return (
      <div key={i} className={`pb-4 ${i < sections.length - 1 ? 'border-b border-gray-100 mb-4' : ''}`}>
        {heading && (
          <h3 className="text-sm font-bold text-blue-700 uppercase tracking-wide mb-2">{heading}</h3>
        )}
        <div className="space-y-1">
          {items.map((line, j) => {
            const clean = line.replace(/^[-*]\s*/, '').replace(/\*\*(.*?)\*\*/g, '$1').trim()
            if (!clean) return null
            const isBullet = /^[-*]/.test(line.trim())
            return (
              <p key={j} className={`text-sm text-gray-700 leading-relaxed ${isBullet ? 'flex gap-2' : ''}`}>
                {isBullet && <span className="text-blue-400 flex-shrink-0 mt-0.5">•</span>}
                <span>{clean}</span>
              </p>
            )
          })}
        </div>
      </div>
    )
  })
}

export default function ActivityLog({ report, reportPath, medlineLinks }) {

  const downloadPDF = () => {
    if (!report) return
    const win = window.open('', '_blank')
    win.document.write(`
      <!DOCTYPE html><html>
      <head>
        <title>Health Report</title>
        <style>
          body { font-family: Arial, sans-serif; max-width: 780px; margin: 40px auto; padding: 0 24px; color: #1a1a1a; line-height: 1.7; }
          h1 { color: #1e40af; font-size: 22px; margin-bottom: 4px; }
          h2 { color: #1d4ed8; font-size: 15px; margin: 24px 0 6px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
          p  { margin: 4px 0; font-size: 14px; }
          ul { margin: 4px 0 4px 20px; font-size: 14px; }
          button { margin-bottom: 20px; padding: 8px 16px; background: #2563eb; color: white; border: none; border-radius: 6px; cursor: pointer; font-size: 14px; }
          @media print { button { display: none; } }
        </style>
      </head>
      <body>
        <button onclick="window.print()">Save as PDF</button>
        <h1>AI Health Intelligence Report</h1>
        <p style="color:#6b7280;font-size:13px;">Generated by Multi-Agent Symptom Journal System</p>
        <hr style="margin:16px 0;border-color:#e5e7eb"/>
        <pre style="white-space:pre-wrap;font-family:Arial;font-size:14px;line-height:1.7">${report.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</pre>
      </body></html>
    `)
    win.document.close()
    setTimeout(() => win.print(), 400)
  }

  return (
    <div className="space-y-4">
      {medlineLinks && medlineLinks.length > 0 && (
        <div className="bg-white rounded-2xl shadow-md p-5">
          <h2 className="text-lg font-bold text-gray-800 mb-3">Health Resources</h2>
          <ul className="space-y-2">
            {medlineLinks.map((link, i) => (
              <li key={i} className="text-sm flex items-center gap-2">
                <span className="text-blue-400">→</span>
                <a href={link.url} target="_blank" rel="noreferrer" className="text-blue-600 hover:underline font-medium">
                  {link.title}
                </a>
                <span className="text-gray-400 capitalize">({link.symptom})</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {report && (
        <div className="bg-white rounded-2xl shadow-md p-5">
          <div className="flex items-center justify-between mb-5">
            <div>
              <h2 className="text-lg font-bold text-gray-800">Health Report</h2>
              {reportPath && (
                <p className="text-xs text-gray-400 font-mono mt-0.5">{reportPath.split(/[/\\]/).pop()}</p>
              )}
            </div>
            <button
              onClick={downloadPDF}
              className="flex items-center gap-1.5 bg-blue-600 text-white text-sm px-3 py-1.5
                         rounded-lg hover:bg-blue-700 transition-colors font-medium"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Download PDF
            </button>
          </div>

          <div className="max-h-[600px] overflow-y-auto bg-gray-50 rounded-xl p-5">
            {renderReport(report)}
          </div>
        </div>
      )}
    </div>
  )
}
